import type { Metadata } from "next";
import { Rethink_Sans } from "next/font/google";
import "./globals.css";
import DarkVeil from "@/components/dark-veil";
import Header from "@/components/header";

const rethink = Rethink_Sans({
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rethink.className} antialiased`}
      >
        <div className="relative w-full h-screen">
          {/* Dark veil behind everything */}
          <div className="absolute inset-0 z-0">
            <DarkVeil hueShift={30} noiseIntensity={0.15} speed={0.75} />
          </div>

          <div className="relative z-10">
            <Header />
            <main className="max-w-3xl mx-auto py-5 px-5 md:px-0">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
